spring.application.name=testingService

server.port=${SERVER_PORT:8002}

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP:localhost:9092}

spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/postgres}

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.IntegerSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer

consumer.group_id=judging_service
solution.judged.event.topic=solution-judged-event-topic

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

logging.level.com.maksim.testingService=debug



#spring.kafka.consumer.group-id=testing-microservice
spring.kafka.consumer.properties.spring.json.trusted.packages=*


spring.data.redis.host=${REDIS_URL:localhost}
spring.data.redis.port=${REDIS_PORT:6379}



